### PR TITLE
o Ploase enter the commit message for your changes. Lines starting

### PR DESCRIPTION
**Pull request by Liam-Cassidy**
Added my proposal.

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
The application is good, but I can't really tell what your software would actually involve, beyond driving OpenFOAM. Simply writing a wrapper for OpenFOAM is not quite a large enough scope for the project. Is there more meat here that I'm missing?

**Comment by Liam-Cassidy** [comment]
Dr. Niemeyer, I understand the concern. My initial plan was to design a software that would (1) import geometry data from a CAD model (or even a formatted Excel sheet), (2) convert the geometry data to an accepted OpenFOAM input format, (3) perform a prescribed mesh and simulation, and (4) produce automated post-processing results.

I now understand your concern for the scope of the project. I've been running OpenFOAM tutorials and reviewing some existing functionality, and it would be appropriate to add a layer of complexity to my scope. 

I was considering revising the scope to have the automated setup/simulation/results live inside an optimization algorithm. I would consider the GHG-equivalent of the specie composition as the "output" metric for stove performance.  The varied inputs would be secondary air flow rate and height of the secondary inlet. 

Please let me know what you think about adding the optimization element to the scope.

**Comment by kyleniemeyer** [comment]
Sure, I think that would make it more interesting. Much of the work here may be in post-processing.

**Comment by Liam-Cassidy** [comment]
Dr. Niemeyer,

That sounds like a good plan. I will go ahead and revise my proposal to reflect the scope changes.

**Comment by kyleniemeyer** [comment]
Is this ready for another look?

**Comment by Liam-Cassidy** [comment]
Yes, it's ready for your review! Let me know about any areas of concern.

**Comment by kyleniemeyer** [comment]
OK, I think this is good now.

**Pull request merged**
