### PR TITLE
This is the submission of my first homework assignment

### PR DESCRIPTION
**Pull request by sebnaran**

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
Can you clarify what the state of the code is vs. what you would be adding during the project? I'm fine with you using the class to work on something for your research, but the class project needs to be substantial in its own right (and not just what you're already working on for your research).

**Comment by sebnaran** [comment]
Hey Kyle,

The code I have written is currently very inefficient. I quite literally have to leave my computer working overnight to get convergence plots. This should not be the case for a 2-D code, specially now that I will be writing a 3-D version. I am unsure as to how to get this done, but I believe that this is what the course is about.

Moreover, as I explain the code I have is of an MFD method and the analysis that I have performed is of a VEM methods, they are very similar but not entirely the same. I am currently trying to write a VEM algorithm that resembles as closely as possible the MFD method that I have.

Concretely the discrepancy lies in a mass matrix, the MFD construction of this mass matrix does not necessarily coincide with the VEM construction. Therefore I will have to create a function that projects my VEM space into my MFD space where I can use the approximations that I already have, or at least this is what I believe to be the case, again this is an ongoing project and the similarities between MFD and VEM continue to be a subject of debate in the community.

Do you think this is a project that I could present in your course?

**Comment by kyleniemeyer** [comment]
If you are planning to write a new version that uses a different method, that would be acceptable.

**Comment by sebnaran** [comment]
I am unsure what is meant by new method, do you mean neither VEM or MFD? or do you mean putting the code that I already have aside and writing a new VEM implementation from scratch?

**Comment by kyleniemeyer** [comment]
My understanding is that you need to write new code that uses the VEM method, is that correct? 

I'm just trying to determine whether there will be substantial dedicated software development for this project, for the class. The intent is not for you to just do the work you were already doing for your research.

**Comment by kyleniemeyer** [comment]
Hi @sebnaran, just wanted to check in on this.

**Comment by sebnaran** [comment]
This is the new version of my project proposal. What do you think?

**Comment by kyleniemeyer** [comment]
OK, this looks reasonable. I would just think about what inputs a user would specify to run different cases.

**Pull request merged**
