### PR TITLE
Update Nepomnyashchikh-project-proposal.md

### PR DESCRIPTION
**Pull request by nepomnyi**
Hello Dr. Niemeyer.

I corrected the proposal as you suggested (clarified what I already have done vs. what I am proposing). I was wondering if you could check it, please?

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
OK, thanks. Do you plan to use the ODE solvers built into scipy?

**Comment by nepomnyi** [comment]
No, the problem is not trivial for an existent solver to be used. I would create my own numerical schematic. Based on my experience with transient model I would prefer not to use existent solvers because a lot of insights can be gained through the process of creating a numerical scheme and coding it. Existent solvers might be good for the final version of the code because they are faster, but for the purpose of flow analysis and mathematical behavior of the drift-flux model, I would definitely be reluctant to use them. Still, if you want me to do it in educational purposes, then I can employ them.

**Comment by kyleniemeyer** [comment]
Got it. No, what you described is fine, I was just curious.

**Comment by nepomnyi** [comment]
Ok, thank you. Should I merge the pull request now?

**Pull request merged**
